name: XMRigMiner-iOS
options:
  bundleIdPrefix: com.iml1s
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_NAME: XMRigMiner
    INFOPLIST_KEY_CFBundleDisplayName: XMRig Multi
    MARKETING_VERSION: "2.3.0"
    CURRENT_PROJECT_VERSION: "23"
    INFOPLIST_FILE: XMRigMiner-iOS/Info.plist
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    SWIFT_OBJC_BRIDGING_HEADER: "XMRigMiner-iOS/Sources/Bridge/XMRigMiner-Bridging-Header.h"
    CLANG_CXX_LANGUAGE_STANDARD: "c++17"
    CLANG_CXX_LIBRARY: "libc++"
    GCC_C_LANGUAGE_STANDARD: "c11"
    HEADER_SEARCH_PATHS:
      - "$(PROJECT_DIR)/XMRigCore/include"
      - "$(PROJECT_DIR)/XMRigCore/build/xmrig-6.25.0/src"
    LIBRARY_SEARCH_PATHS:
      - "$(PROJECT_DIR)/XMRigCore/output"

targets:
  XMRigMiner:
    type: application
    platform: iOS
    sources:
      - path: XMRigMiner-iOS/Sources
        excludes:
          - "**/.DS_Store"
      - path: Shared
      - path: XMRigCore/include
        type: group
        buildPhase: none
    entitlements:
      path: XMRigMiner-iOS/XMRigMiner.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iml1s.xmrigminer
        TARGETED_DEVICE_FAMILY: "1,2"
        ONLY_ACTIVE_ARCH: NO
        ENABLE_BITCODE: NO
        CODE_SIGN_ENTITLEMENTS: XMRigMiner-iOS/XMRigMiner.entitlements
        OTHER_LDFLAGS:
          - "-lxmrig-ios-arm64"
          - "-lc++"
        ARCHS: arm64
        VALID_ARCHS: arm64
    info:
      path: XMRigMiner-iOS/Info.plist
    dependencies:
      - target: XMRigMinerWidgets
        embed: true
        codeSign: true
      - sdk: WidgetKit.framework
      - sdk: ActivityKit.framework

  XMRigMinerWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: XMRigMinerWidgets
        excludes:
          - "**/.DS_Store"
      - path: Shared
    entitlements:
      path: XMRigMinerWidgets/XMRigMinerWidgets.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iml1s.xmrigminer.widgets
        SKIP_INSTALL: YES
        CODE_SIGN_ENTITLEMENTS: XMRigMinerWidgets/XMRigMinerWidgets.entitlements
        INFOPLIST_KEY_CFBundleDisplayName: XMRig Glance
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"
    info:
      properties:
        CFBundleDisplayName: XMRig Glance
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
      - sdk: AppIntents.framework
      - sdk: ActivityKit.framework

schemes:
  XMRigMiner:
    build:
      targets:
        XMRigMiner: all
        XMRigMinerWidgets: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
